services:
  # Primer nodo del API
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - INSTANCE_NAME=${HOSTNAME}
      - ASPNETCORE_URLS=http://+:80
    # ports:
    #   - "8080:80"
    expose:
      - "80"  
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Gateway con Load Balancer
  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    ports:
      - "8010:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

